set(work "${GENERATED_DIR}/${CASE}")
file(REMOVE_RECURSE "${work}")
file(MAKE_DIRECTORY "${work}")
set(defines)
if(CASE STREQUAL "fp_sqrt")
    set(source "examples/math/FpSqrt.cpp")
elseif(CASE STREQUAL "numeric" OR CASE STREQUAL "numeric_instantiated")
    set(source "tests/templates/StandaloneNumeric.h")
    if(CASE STREQUAL "numeric_instantiated")
        set(defines -- -DINSTANTIATE_NUMERIC)
    endif()
else()
    message(FATAL_ERROR "Unknown standalone template case: ${CASE}")
endif()

# Deliberately omit -I and use the user's --generated-dir= spelling. Never
# consult checked-in generated files or native-only testbench instantiations.
execute_process(COMMAND "${CPPHDL}" "--generated-dir=${work}/generated" "${source}" ${defines}
    WORKING_DIRECTORY "${SOURCE_ROOT}"
    RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
if(NOT result EQUAL 0)
    message(FATAL_ERROR "Standalone conversion failed:\n${output}\n${error}")
endif()

function(require_rtl module)
    set(path "${work}/generated/${module}.sv")
    if(NOT EXISTS "${path}")
        message(FATAL_ERROR "Converter succeeded without generating ${path}:\n${output}\n${error}")
    endif()
    file(READ "${path}" rtl)
    if(rtl MATCHES "unknown:|RecoveryExpr")
        message(FATAL_ERROR "Unconverted expression in ${path}:\n${rtl}")
    endif()
    set(rtl "${rtl}" PARENT_SCOPE)
endfunction()

function(lint module)
    if(VERILATOR)
        file(GLOB packages "${work}/generated/*_pkg.sv")
        list(REMOVE_ITEM packages "${work}/generated/Predef_pkg.sv")
        execute_process(COMMAND "${VERILATOR}" --lint-only --Wno-fatal
            --top-module "${module}" ${ARGN}
            "${work}/generated/Predef_pkg.sv" ${packages} "${work}/generated/${module}.sv"
            RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
        if(NOT result EQUAL 0)
            message(FATAL_ERROR "Invalid standalone RTL:\n${output}\n${error}")
        endif()
    endif()
endfunction()

if(CASE STREQUAL "fp_sqrt")
    require_rtl(FpSqrt)
    if(NOT rtl MATCHES "parameter W = ('h20|32)\n" OR NOT rtl MATCHES "parameter EW = ('h8|8)\n")
        message(FATAL_ERROR "FpSqrt's declared FP32 defaults were not preserved:\n${rtl}")
    endif()
    lint(FpSqrt)
    lint(FpSqrt -GW=16 -GEW=5)
    lint(FpSqrt -GW=32 -GEW=8)
    if(FP_SQRT_TEST)
        execute_process(COMMAND "${CMAKE_COMMAND}" -E env
            "CPPHDL_VERILATOR_CFLAGS=$ENV{CPPHDL_VERILATOR_CFLAGS} -I${SOURCE_ROOT}/include"
            "${FP_SQRT_TEST}"
            WORKING_DIRECTORY "${work}"
            RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
        if(NOT result EQUAL 0)
            message(FATAL_ERROR "FP16/FP32 C++/Verilator checks failed:\n${output}\n${error}")
        endif()
    endif()
else()
    require_rtl(StandaloneNumeric)
    if(CASE STREQUAL "numeric_instantiated")
        if(NOT rtl MATCHES "parameter WIDTH = 12")
            message(FATAL_ERROR "Primary template overwrote the concrete specialization:\n${rtl}")
        endif()
    elseif(NOT rtl MATCHES "parameter WIDTH\n")
        message(FATAL_ERROR "Required WIDTH parameter missing:\n${rtl}")
    endif()
    if(NOT rtl MATCHES "parameter BIAS = ('h3|3)")
        message(FATAL_ERROR "BIAS default missing:\n${rtl}")
    endif()
    lint(StandaloneNumeric -GWIDTH=16)
    require_rtl(StandaloneArray)
    if(NOT rtl MATCHES "parameter WIDTH = ('h8|8)" OR NOT rtl MATCHES "parameter COUNT = ('h2|2)")
        message(FATAL_ERROR "Array template defaults missing:\n${rtl}")
    endif()
    lint(StandaloneArray)
    require_rtl(StandaloneStructArray)
    if(NOT rtl MATCHES "import StandaloneWord_pkg::")
        message(FATAL_ERROR "Packed array element's struct package was not imported:\n${rtl}")
    endif()
    lint(StandaloneStructArray)
    require_rtl(StandaloneInterface)
    if(NOT rtl MATCHES "source_out__data_out" OR NOT rtl MATCHES "sink_in__ready_out")
        message(FATAL_ERROR "Dependent interface ports were not flattened:\n${rtl}")
    endif()
    lint(StandaloneInterface)
    if(EXISTS "${work}/generated/StandaloneTyped.sv")
        message(FATAL_ERROR "A module with an unresolved type parameter was emitted")
    endif()
    foreach(module StandaloneDependentBase StandaloneDependentChild)
        if(CASE STREQUAL "numeric_instantiated")
            require_rtl(${module})
        elseif(EXISTS "${work}/generated/${module}.sv")
            message(FATAL_ERROR "A module needing concrete class dependencies was emitted: ${module}")
        endif()
    endforeach()
endif()
