include("${TOOLCHAIN}")
file(REMOVE_RECURSE "${WORK}")
file(MAKE_DIRECTORY "${WORK}")
set(definitions)
if(MISSING_CAPACITY)
    list(APPEND definitions -DHLS_NO_CAPACITY)
endif()
execute_process(COMMAND "${CPPHDL}" --hls --generated-dir "${WORK}"
    "${CMAKE_CURRENT_LIST_DIR}/${CONTAINER}.cpp" -- "-I${ROOT}/include" ${definitions} ${HLS_PARSE_FLAGS}
    RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
file(WRITE "${WORK}/conversion.log" "${output}\n${error}")
if(NOT result STREQUAL "1" OR NOT error MATCHES "HLS error: actual std::container methods were collected")
    message(FATAL_ERROR "Expected a precise unsupported-RTL diagnostic, not a crash or stub:\n${output}\n${error}")
endif()
if(error MATCHES ":[0-9]+:[0-9]+: error:")
    message(FATAL_ERROR "Analysis must not instantiate invalid or unevaluated library code:\n${error}")
endif()
file(GLOB rtl "${WORK}/*.sv")
if(rtl)
    message(FATAL_ERROR "Unsupported STL lowering must not emit placeholder RTL: ${rtl}")
endif()
file(READ "${WORK}/hls-analysis.json" report)
string(JSON status GET "${report}" status)
if(NOT status STREQUAL "unsupported_rtl")
    message(FATAL_ERROR "Analysis must not claim successful synthesis")
endif()
string(JSON object GET "${report}" translation_units 0 objects 0)
string(JSON storage GET "${object}" storage)
string(JSON capacity GET "${object}" capacity)
if(NOT storage STREQUAL "registers")
    message(FATAL_ERROR "Member object policy lost")
endif()
if(MISSING_CAPACITY)
    if(NOT report MATCHES "missing_capacity")
        message(FATAL_ERROR "Missing bounded-capacity diagnostic")
    endif()
elseif(NOT capacity EQUAL 8)
    message(FATAL_ERROR "Object's capacity annotation was lost")
endif()
string(JSON methods GET "${report}" translation_units 0 methods)
string(JSON count LENGTH "${methods}")
if(count LESS 5)
    message(FATAL_ERROR "Actual transitive STL methods were not collected")
endif()
if(CONTAINER MATCHES "^(Vector|List)$")
    set(required "push_back;erase;size;clear")
else()
    set(required "find;emplace;erase;size;clear")
endif()
foreach(method IN LISTS required)
    set(found FALSE)
    math(EXPR last "${count} - 1")
    foreach(i RANGE ${last})
        string(JSON id GET "${methods}" ${i} id)
        if(id MATCHES "^std::declval[<( :]")
            message(FATAL_ERROR "Unevaluated declval must not enter the runtime method graph")
        endif()
        string(JSON has_body GET "${methods}" ${i} has_body)
        if(id MATCHES "::${method}([<( :])" AND has_body)
            set(found TRUE)
        endif()
    endforeach()
    if(NOT found)
        message(FATAL_ERROR "No actual instantiated body for ${method}")
    endif()
endforeach()
if(CONTAINER MATCHES "^(Map|Multimap)$")
    foreach(field __left_ __right_ __parent_ __is_black_)
        if(NOT report MATCHES "\"name\": \"${field}\"")
            message(FATAL_ERROR "Actual RB-tree node field ${field} was not collected")
        endif()
    endforeach()
    foreach(method __tree_balance_after_insert __tree_remove)
        if(NOT methods MATCHES "${method}")
            message(FATAL_ERROR "RB-tree implementation dependency ${method} was not followed")
        endif()
    endforeach()
endif()
if(CONTAINER MATCHES "^(Map|Multimap)$")
    foreach(helper __tree_balance_after_insert __tree_remove __tree_left_rotate __tree_right_rotate)
        set(found FALSE)
        foreach(i RANGE ${last})
            string(JSON id GET "${methods}" ${i} id)
            string(JSON has_body GET "${methods}" ${i} has_body)
            if(id MATCHES "::${helper}([<( :])" AND has_body)
                set(found TRUE)
            endif()
        endforeach()
        if(NOT found)
            message(FATAL_ERROR "libc++ headers must provide the actual ${helper} body")
        endif()
    endforeach()
endif()
if(NOT report MATCHES "storage_lowering_unimplemented")
    message(FATAL_ERROR "Missing storage/scheduling blocker")
endif()
message(STATUS "Collected ${count} real STL functions; unsupported RTL correctly rejected")
