file(MAKE_DIRECTORY "${WORK}")
set(source "${ROOT}/synth/tests/hls/AutoScheduler.cpp")
foreach(top AutoTop auto_root)
    foreach(mode synthesis scheduled)
        set(graph "${WORK}/${top}-${mode}.cc")
        file(REMOVE "${graph}")
        execute_process(COMMAND "${CPPHDL}" "--lower-${mode}-graph" "${source}" "${graph}" "${top}"
            -- -std=c++17 -DSYNTHESIS "-I${ROOT}/include"
            RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error TIMEOUT 60)
        if(NOT result EQUAL 0)
            message(FATAL_ERROR "${top}/${mode} graph export failed:\n${output}\n${error}")
        endif()
        file(READ "${graph}" ${mode})
    endforeach()
    if(NOT synthesis STREQUAL scheduled OR NOT synthesis MATCHES "streams_v1")
        message(FATAL_ERROR "Automatic scheduling changed or omitted the scheduled graph")
    endif()
endforeach()
# Unused HLS classes in the same source must not change ordinary RTL lowering.
foreach(mode synthesis cpp)
    set(graph "${WORK}/plain-${mode}.cc")
    file(REMOVE "${graph}")
    execute_process(COMMAND "${CPPHDL}" "--lower-${mode}-graph" "${source}" "${graph}" plain_root
        -- -std=c++17 -DSYNTHESIS "-I${ROOT}/include"
        RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error TIMEOUT 60)
    if(NOT result EQUAL 0)
        message(FATAL_ERROR "Ordinary RTL ${mode} export failed:\n${output}\n${error}")
    endif()
    file(READ "${graph}" ${mode})
endforeach()
if(NOT synthesis STREQUAL cpp)
    message(FATAL_ERROR "Unused wrappers changed ordinary RTL graph lowering")
endif()
file(REMOVE "${WORK}/native.cc")
execute_process(COMMAND "${CPPHDL}" --lower-cpp-graph "${source}" "${WORK}/native.cc" auto_root
    -- -std=c++17 "-I${ROOT}/include"
    RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error TIMEOUT 60)
if(result EQUAL 0 OR NOT error MATCHES "requires the scheduled HLS graph")
    message(FATAL_ERROR "Native graph lowering must not synthesize the transaction reference: ${error}")
endif()
foreach(mode ordinary synth)
    set(options)
    if(mode STREQUAL "synth")
        set(options --synth --top AutoTop --output "${WORK}/removed-flag")
    endif()
    execute_process(COMMAND "${CPPHDL}" ${options} --hls "${source}"
        RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error TIMEOUT 20)
    if(result EQUAL 0 OR NOT error MATCHES "(Unknown|unknown|unrecognized).*--hls")
        message(FATAL_ERROR "Removed flag must be rejected by ${mode}: ${output}\n${error}")
    endif()
endforeach()
