# Verilator may emit fewer translation units after a scheduler change. Old
# archive members must not survive and refer to the previous model's types.
file(REMOVE_RECURSE "${WORK}/generated" "${WORK}/obj_dir")
file(MAKE_DIRECTORY "${WORK}/generated")
foreach(log conversion verilator build simulation)
    file(WRITE "${WORK}/${log}.log" "")
endforeach()
include("${TOOLCHAIN}")
get_filename_component(stem "${SOURCE}" NAME_WE)
execute_process(COMMAND "${CPPHDL}" --hls --generated-dir "${WORK}/generated" "${SOURCE}"
    -- "-I${ROOT}/include" -fno-exceptions ${HLS_PARSE_FLAGS}
    RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
file(WRITE "${WORK}/conversion.log" "${output}\n${error}")
if(NOT result EQUAL 0)
    message(FATAL_ERROR "AST conversion failed:\n${output}\n${error}")
endif()
file(GLOB generated "${WORK}/generated/*Clocked*Methods*.sv")
list(LENGTH generated count)
set(expected_count 1)
if(stem STREQUAL "ClockedRecursion")
    set(expected_count 2)
endif()
if(NOT count EQUAL expected_count)
    message(FATAL_ERROR "Expected ${expected_count} clocked container modules, found ${generated}")
endif()
set(rtl "")
foreach(module IN LISTS generated)
    file(READ "${module}" source)
    if(NOT source MATCHES "// Shared lowering: ([0-9]+) bodies, ([0-9]+) function bodies")
        message(FATAL_ERROR "Missing shared-function schedule statistics")
    endif()
    if(NOT CMAKE_MATCH_2 LESS CMAKE_MATCH_1)
        message(FATAL_ERROR "Repeated clocked calls were not shared in ${module}")
    endif()
    string(REGEX MATCH "function static void hls_[A-Za-z0-9_]+__shared_[0-9]+" first_body "${source}")
    if(NOT first_body)
        message(FATAL_ERROR "Missing shared scheduled functions in ${module}")
    endif()
    string(FIND "${source}" "${first_body}" body_start)
    string(FIND "${source}" "always_comb" body_end)
    math(EXPR body_size "${body_end} - ${body_start}")
    string(SUBSTRING "${source}" ${body_start} ${body_size} bodies)
    if(bodies MATCHES "storage\\[")
        message(FATAL_ERROR "Scheduled method still expands raw byte accesses in ${module}")
    endif()
    string(APPEND rtl "${source}\n")
endforeach()
set(top "${stem}Top")
if(NOT rtl MATCHES "// instantiated: std::" OR NOT rtl MATCHES "// loop boundary")
    message(FATAL_ERROR "Expected instantiated standard-library methods and loop continuations")
endif()
string(REGEX REPLACE "//[^\n]*" "" named_rtl "${rtl}")
if(named_rtl MATCHES "__this_addr_|(^|[^A-Za-z0-9_])pc_reg([^A-Za-z0-9_]|$)|@hls_access_")
    message(FATAL_ERROR "Unresolved source access or indirect this/program counter lowering")
endif()
if(stem STREQUAL "ClockedBindings")
    if(NOT named_rtl MATCHES "values_reg\\.hls_BindingsCounter__repeat__call_[0-9]+_depth_1__i_[0-9]+")
        message(FATAL_ERROR "Loop index must remain live across the repeated method's clocks")
    endif()
    if(named_rtl MATCHES "localparam[^\n]+__(selected|amount)_addr_")
        message(FATAL_ERROR "Direct pointer/reference bindings must not allocate parameter memory")
    endif()
endif()
if(NOT rtl MATCHES "// Source values: ([0-9]+) direct scalars, ([0-9]+) live across clocks")
    message(FATAL_ERROR "Missing direct source variable lowering")
endif()
if(NOT CMAKE_MATCH_2 LESS CMAKE_MATCH_1)
    message(FATAL_ERROR "Not every scalar temporary needs a register")
endif()
if(named_rtl MATCHES "(^|[^A-Za-z0-9_])(automatic|ref)([^A-Za-z0-9_]|$)")
    message(FATAL_ERROR "Clocked RTL must use static functions with input/inout arguments, not automatic/ref")
endif()
if(named_rtl MATCHES "function static void step_[0-9]" OR named_rtl MATCHES "scratch\\.t[0-9]+")
    message(FATAL_ERROR "Source method/variable names were replaced with anonymous numbering")
endif()
if(NOT named_rtl MATCHES "function static void hls_[A-Za-z0-9_]+__command__shared_[0-9]+")
    message(FATAL_ERROR "Missing executable source-named command function")
endif()
if(stem STREQUAL "ClockedArray" OR stem STREQUAL "ClockedVector")
    foreach(variable bias value i)
        if(NOT named_rtl MATCHES "logic \\[[0-9]+:0\\] values__hls_[A-Za-z0-9_]+__sum__call_[0-9]+_depth_1__${variable}_[0-9]+;")
            message(FATAL_ERROR "Missing direct named sum parameter/local: ${variable}")
        endif()
        if(named_rtl MATCHES "localparam[^\n]+__sum__call_[0-9]+_depth_1__${variable}_addr_")
            message(FATAL_ERROR "Unaddressed scalar ${variable} must not be allocated in memory")
        endif()
    endforeach()
endif()
if(stem STREQUAL "ClockedVector")
    foreach(field __begin_ __end_ __cap_)
        if(NOT rtl MATCHES "// field: [^\n]*${field} byte offset")
            message(FATAL_ERROR "Expected the actual libc++ vector field ${field}")
        endif()
    endforeach()
endif()
if(stem STREQUAL "ClockedMap")
    if(rtl MATCHES "_Rb_tree|tree\\.cc")
        message(FATAL_ERROR "Map must use libc++ header algorithms, not bundled libstdc++ sources")
    endif()
    foreach(helper __tree_min __tree_next_iter __tree_balance_after_insert __tree_remove __tree_left_rotate __tree_right_rotate destroy)
        if(NOT rtl MATCHES "// instantiated: [^\n]*${helper}")
            message(FATAL_ERROR "Missing actual tree algorithm: ${helper}")
        endif()
        if(NOT named_rtl MATCHES "function static void hls_[A-Za-z0-9_]*${helper}__shared_[0-9]+")
            message(FATAL_ERROR "Tree method name exists only in comments: ${helper}")
        endif()
    endforeach()
    foreach(field __left_ __right_ __parent_ __is_black_)
        if(NOT rtl MATCHES "// field: [^\n]*${field}")
            message(FATAL_ERROR "Missing actual tree node field: ${field}")
        endif()
        if(NOT named_rtl MATCHES "\\+ hls_field_[A-Za-z0-9_]*${field}_offset_[0-9]+")
            message(FATAL_ERROR "Tree field name is missing from actual address calculation: ${field}")
        endif()
    endforeach()
endif()
if(stem STREQUAL "ClockedReuse")
    foreach(method _S_left inspect)
        string(REGEX MATCHALL "function static void hls_ReuseNode__${method}__shared_[0-9]+" definitions "${named_rtl}")
        list(LENGTH definitions count)
        if(NOT count EQUAL 1)
            message(FATAL_ERROR "Expected one complete ${method} function, not call/return fragments: ${count}")
        endif()
        string(FIND "${named_rtl}" "${definitions}" start)
        string(SUBSTRING "${named_rtl}" ${start} -1 rest)
        string(FIND "${rest}" "endfunction" end)
        string(SUBSTRING "${rest}" 0 ${end} body)
        if(body MATCHES "active|next_block|else_block|phase")
            message(FATAL_ERROR "Non-suspending method ${method} must not contain scheduler controls")
        endif()
        if(NOT body MATCHES "if \\(")
            message(FATAL_ERROR "Missing structured branch in ${method}")
        endif()
    endforeach()
    if(named_rtl MATCHES "function static void hls_ReuseNode___M_node_ptr__shared_")
        message(FATAL_ERROR "return this must not produce a standalone identity-copy function")
    endif()
    foreach(width 8 16 32 64 128)
        foreach(operation read write)
            string(REGEX MATCHALL "function static [^\n]+ hls_storage_${operation}_${width}\\(" helpers "${named_rtl}")
            list(LENGTH helpers count)
            if(NOT count EQUAL 1)
                message(FATAL_ERROR "Expected one shared ${width}-bit storage ${operation} helper, got ${count}")
            endif()
        endforeach()
    endforeach()
    foreach(method mix widen)
        string(REGEX MATCHALL "function static void hls_ReuseMethods__${method}__shared_[0-9]+" definitions "${named_rtl}")
        list(LENGTH definitions count)
        set(expected 1)
        if(method STREQUAL "widen")
            set(expected 2)
        endif()
        if(NOT count EQUAL expected)
            message(FATAL_ERROR "Expected ${expected} ${method} bodies, got ${count}")
        endif()
    endforeach()
    if(NOT named_rtl MATCHES "inout logic \\[31:0\\] p_[A-Za-z0-9_]+" OR
       NOT named_rtl MATCHES "input logic \\[63:0\\] p_[A-Za-z0-9_]+_addr_[0-9]+")
        message(FATAL_ERROR "Shared bodies must parameterize values and source object addresses")
    endif()
endif()
file(GLOB ir "${WORK}/generated/*.ll")
if(ir)
    message(FATAL_ERROR "AST scheduling must not produce LLVM IR")
endif()
execute_process(COMMAND "${CXX}" -print-file-name=libatomic.so OUTPUT_VARIABLE atomic OUTPUT_STRIP_TRAILING_WHITESPACE)
get_filename_component(atomic_dir "${atomic}" DIRECTORY)
file(GLOB packages "${WORK}/generated/*_pkg.sv")
# Preserve shared method bodies during host model compilation.
set(verilator_options -fno-inline-funcs)
list(JOIN HLS_CXX_FLAGS " " cxx_flags)
list(JOIN HLS_LINK_FLAGS " " link_flags)
execute_process(COMMAND "${VERILATOR}" --cc --exe --top-module "${top}" --prefix VClockedModel
    --Mdir "${WORK}/obj_dir" -Wno-fatal ${verilator_options}
    -CFLAGS "${cxx_flags} -I${ROOT}/include -DVERILATOR"
    -LDFLAGS "${link_flags} -L${atomic_dir}"
    ${packages} ${generated} "${WORK}/generated/${top}.sv" "${SOURCE}"
    RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
file(WRITE "${WORK}/verilator.log" "${output}\n${error}")
if(NOT result EQUAL 0)
    message(FATAL_ERROR "Verilator failed:\n${output}\n${error}")
endif()
if(error MATCHES "Warning-(MULTIDRIVEN|LATCH)")
    message(FATAL_ERROR "Scheduled RTL must not introduce multiple drivers or latches:\n${error}")
endif()
execute_process(COMMAND "${MAKE}" -C "${WORK}/obj_dir" -f VClockedModel.mk -j2 "CXX=${CXX}" "LINK=${CXX}"
    RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
file(WRITE "${WORK}/build.log" "${output}\n${error}")
if(NOT result EQUAL 0)
    message(FATAL_ERROR "Build failed:\n${output}\n${error}")
endif()
execute_process(COMMAND "${WORK}/obj_dir/VClockedModel"
    RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
file(WRITE "${WORK}/simulation.log" "${output}\n${error}")
if(NOT result EQUAL 0)
    message(FATAL_ERROR "Simulation failed:\n${output}\n${error}")
endif()
message(STATUS "${output}")
if(stem STREQUAL "ClockedReuse")
    include("${CMAKE_CURRENT_LIST_DIR}/StorageHelpers.cmake")
endif()
