# Verilator may emit fewer translation units after a scheduler change. Old
# archive members must not survive and refer to the previous model's types.
file(REMOVE_RECURSE "${WORK}/generated" "${WORK}/obj_dir")
file(MAKE_DIRECTORY "${WORK}/generated")
foreach(log conversion verilator build simulation)
    file(WRITE "${WORK}/${log}.log" "")
endforeach()
include("${TOOLCHAIN}")
if(SHARED_MEMORY)
    list(APPEND HLS_PARSE_FLAGS -DHLS_SHARED_MEMORY=1)
    list(APPEND HLS_CXX_FLAGS -DHLS_SHARED_MEMORY=1)
endif()
if(BLOCK_RAM)
    list(APPEND HLS_PARSE_FLAGS -DHLS_BLOCK_RAM=1)
    list(APPEND HLS_CXX_FLAGS -DHLS_BLOCK_RAM=1)
endif()
get_filename_component(stem "${SOURCE}" NAME_WE)
execute_process(COMMAND "${CPPHDL}" --generated-dir "${WORK}/generated" "${SOURCE}"
    -- "-I${ROOT}/include" -fno-exceptions ${HLS_PARSE_FLAGS}
    RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
file(WRITE "${WORK}/conversion.log" "${output}\n${error}")
if(NOT result EQUAL 0)
    message(FATAL_ERROR "AST conversion failed:\n${output}\n${error}")
endif()
file(GLOB generated "${WORK}/generated/*Clocked*Methods*.sv")
list(LENGTH generated count)
set(expected_count 1)
if(stem STREQUAL "DelayedRecursion" OR stem STREQUAL "DelayedAddress")
    set(expected_count 2)
endif()
if(NOT count EQUAL expected_count)
    message(FATAL_ERROR "Expected ${expected_count} clocked container modules, found ${generated}")
endif()
set(rtl "")
foreach(module IN LISTS generated)
    file(READ "${module}" source)
    if(stem STREQUAL "DelayedMemoryEffects" AND NOT source MATCHES "// Memory effects: [1-9][0-9]* redundant loads reused")
        message(FATAL_ERROR "Memory-effect regression did not eliminate any redundant load")
    endif()
    if(stem STREQUAL "DelayedSharing" AND SHARED_MEMORY)
        foreach(expected "SharingMethods__mutate depth 1, 3 callers" "SharingMethods__conditional depth 1, 3 callers")
            if(NOT source MATCHES "// Shared clocked body: ${expected}")
                message(FATAL_ERROR "Missing hardware-shared call body: ${expected}")
            endif()
        endforeach()
        if(source MATCHES "hls_SharingMethods__mutate__call_[0-9]+_depth_1")
            message(FATAL_ERROR "Pointer writer still has duplicated call-local state")
        endif()
        if(source MATCHES "// Shared clocked body: SharingMethods__typed")
            message(FATAL_ERROR "Known local pointer arguments must retain direct-object promotion")
        endif()
    endif()
    if(stem STREQUAL "DelayedRecursion" AND SHARED_MEMORY)
        set(depth_bound 4)
        if(module MATCHES "_R2_")
            set(depth_bound 2)
        endif()
        foreach(method branching descend)
            string(REGEX MATCHALL "// Recursive body: RecursionMethods__${method} depth [0-9]+, [0-9]+ callers" bodies "${source}")
            list(LENGTH bodies body_count)
            if(NOT body_count EQUAL depth_bound)
                message(FATAL_ERROR "${method} must have exactly one reusable body per depth, got ${body_count}")
            endif()
            string(REGEX MATCHALL "    logic \\[31:0\\] hls_RecursionMethods__${method}__shared_[0-9]+_depth_[0-9]+__depth_[0-9]+;" depth_registers "${source}")
            list(FILTER depth_registers EXCLUDE REGEX "^$")
            list(LENGTH depth_registers register_count)
            if(NOT register_count EQUAL depth_bound)
                message(FATAL_ERROR "${method} must store one depth parameter per reusable body, got ${register_count}")
            endif()
        endforeach()
        foreach(depth RANGE 1 ${depth_bound})
            if(NOT source MATCHES "// Recursive body: RecursionMethods__branching depth ${depth}, 2 callers")
                message(FATAL_ERROR "Both branching calls must share the same depth ${depth} implementation")
            endif()
        endforeach()
        if(NOT source MATCHES "// recursive call boundary")
            message(FATAL_ERROR "Shared recursive calls require an explicit scheduling boundary")
        endif()
    endif()
    set(address_bits 64)
    if(module MATCHES "_A16(_|[.])")
        set(address_bits 16)
    elseif(module MATCHES "_A32(_|[.])")
        set(address_bits 32)
    endif()
    if(NOT source MATCHES "localparam int ADDR_BITS = ${address_bits};"
       OR NOT source MATCHES "logic \\[ADDR_BITS-1:0\\] heap_next, heap_next_reg;"
       OR NOT source MATCHES "input logic \\[ADDR_BITS-1:0\\] address"
       OR NOT source MATCHES "output wire \\[63:0\\] result_out")
        message(FATAL_ERROR "Address width or independent 64-bit result width is incorrect in ${module}")
    endif()
    math(EXPR address_msb "${address_bits} - 1")
    if(address_bits LESS 64 AND source MATCHES "localparam logic \\[63:0\\]")
        message(FATAL_ERROR "A generated address constant still uses 64 bits in ${module}")
    endif()
    if(stem STREQUAL "DelayedAddress" AND NOT source MATCHES "logic \\[${address_msb}:0\\] [A-Za-z0-9_]*__p_[0-9]+;")
        message(FATAL_ERROR "Loop pointer must use the selected address width in ${module}")
    endif()
    if(stem STREQUAL "DelayedAddress" AND SHARED_MEMORY)
        string(REGEX MATCHALL "logic \\[[0-9]+:0\\] scratch__port_pointer_value_[0-9]+" pointer_values "${source}")
        if(NOT pointer_values)
            message(FATAL_ERROR "Missing pointer load temporaries in ${module}")
        endif()
        foreach(value IN LISTS pointer_values)
            if(NOT value MATCHES "logic \\[${address_msb}:0\\]")
                message(FATAL_ERROR "Pointer access temporary still uses host pointer width: ${value}")
            endif()
        endforeach()
    endif()
    if(SOURCE MATCHES "/std/" AND NOT address_bits EQUAL 16)
        message(FATAL_ERROR "Standard-container examples must use 16-bit addresses")
    endif()
    if(NOT source MATCHES "typedef struct packed [{][^}]+[}] clocked_values_t;"
       OR source MATCHES "typedef struct[ \t\r\n]+[{]")
        message(FATAL_ERROR "Clocked register state must use a packed struct in ${module}")
    endif()
    if(source MATCHES "storage_t storage, storage_reg" OR source MATCHES "hls_storage_write_[0-9]+")
        message(FATAL_ERROR "Memory writes must not pass and replace the complete byte arena")
    endif()
    foreach(bank RANGE 0 7)
        if(BLOCK_RAM)
            if(NOT source MATCHES "ram_style = \"block\"" OR
               NOT source MATCHES "no_rw_check" OR
               NOT source MATCHES "&& !hls_ram_write_enable;" OR
               NOT source MATCHES "__HlsRamByte #\\(.*\\) storage_lane${bank}_ram" OR
               NOT source MATCHES "logic \\[7:0\\] data \\[0:DEPTH-1\\];" OR
               NOT source MATCHES "if \\(read_enable\\) read_data <= data\\[address\\];" OR
               NOT source MATCHES "if \\(write_enable\\) data\\[address\\] <= write_data;")
                message(FATAL_ERROR "Missing synchronous RAM read/write port for lane ${bank}")
            endif()
        elseif(NOT source MATCHES "bank_t storage_lane${bank}, storage_lane${bank}_reg;")
            message(FATAL_ERROR "Missing independent byte-lane state ${bank}")
        endif()
    endforeach()
    if(SHARED_MEMORY)
        if(source MATCHES "input logic \\[CALL_RESULT_BITS-1:0\\] hls_call_result")
            message(FATAL_ERROR "Each shared helper needs scratch sized for its own callees, not a design-wide maximum")
        endif()
        string(REGEX MATCH "localparam int CALL_RESULT_BITS = ([0-9]+);" result_width "${source}")
        set(actual_result_bits "${CMAKE_MATCH_1}")
        string(REGEX MATCHALL "function static logic \\[[0-9+A-Z_]+-1:0\\] hls_[A-Za-z0-9_]+__shared_[0-9]+" result_functions "${source}")
        set(expected_result_bits 1)
        foreach(declaration IN LISTS result_functions)
            string(REGEX REPLACE ".*\\[([^]]+)-1:0\\].*" "\\1" width "${declaration}")
            string(REPLACE "ADDR_BITS" "${address_bits}" width "${width}")
            math(EXPR width "${width}")
            if(width GREATER expected_result_bits)
                set(expected_result_bits "${width}")
            endif()
        endforeach()
        if(NOT actual_result_bits EQUAL expected_result_bits)
            message(FATAL_ERROR "Shared call scratch must match actual function results, not the arena: ${actual_result_bits} != ${expected_result_bits}")
        endif()
        if(NOT source MATCHES "memory_commit_fault" OR NOT source MATCHES "// memory port boundary")
            message(FATAL_ERROR "Shared memory requires a checked port and explicit access boundaries")
        endif()
        if(source MATCHES "input bank_t storage_lane")
            # The sole load helper owns the bank inputs, not scheduled methods.
            string(REGEX MATCH "function static [^\n]+ hls_[A-Za-z0-9_]+__shared_[0-9]+" first_method "${source}")
            string(FIND "${source}" "${first_method}" method_start)
            string(SUBSTRING "${source}" ${method_start} -1 methods)
            if(methods MATCHES "input bank_t")
                message(FATAL_ERROR "Scheduled methods must not copy the shared memory banks")
            endif()
        endif()
        foreach(pin operation_in index_in value_in)
            if(NOT source MATCHES "hls_accepted_${pin} <= ${pin};")
                message(FATAL_ERROR "Command pin ${pin} must be captured before any memory wait")
            endif()
        endforeach()
        string(REGEX MATCHALL "hls_storage_address_valid\\(" checks "${source}")
        list(LENGTH checks check_count)
        if(NOT check_count EQUAL 2)
            message(FATAL_ERROR "Expected one bounds function and one shared checker call, got ${check_count}")
        endif()
        string(REGEX MATCHALL "hls_storage_load_[0-9]+\\(" reads "${source}")
        list(LENGTH reads read_count)
        if(BLOCK_RAM AND NOT read_count EQUAL 0)
            message(FATAL_ERROR "BRAM must use synchronous bank reads, not whole-bank function inputs")
        elseif(NOT BLOCK_RAM AND NOT read_count EQUAL 2)
            message(FATAL_ERROR "Expected one load function and one physical read port, got ${read_count}")
        endif()
        foreach(bank RANGE 0 7)
            string(REGEX MATCHALL "hls_bank_write_port_${bank}\\(" writes "${source}")
            list(LENGTH writes write_count)
            if(BLOCK_RAM AND NOT write_count EQUAL 0)
                message(FATAL_ERROR "BRAM must write selected bytes, not replace whole banks")
            elseif(NOT BLOCK_RAM AND NOT write_count EQUAL 2)
                message(FATAL_ERROR "Expected one writer and one physical write port for lane ${bank}")
            endif()
        endforeach()
    endif()
    if(NOT source MATCHES "// Shared lowering: ([0-9]+) bodies, ([0-9]+) function bodies")
        message(FATAL_ERROR "Missing shared-function schedule statistics")
    endif()
    if(NOT CMAKE_MATCH_2 LESS CMAKE_MATCH_1)
        message(FATAL_ERROR "Repeated clocked calls were not shared in ${module}")
    endif()
    string(REGEX MATCHALL "always_comb begin : hls_step_[0-9]+" steps "${source}")
    list(LENGTH steps step_count)
    if(NOT source MATCHES "// Shared schedule: ([0-9]+) blocks" OR NOT step_count EQUAL CMAKE_MATCH_1)
        message(FATAL_ERROR "Each scheduled block needs an independent combinational process in ${module}")
    endif()
    string(REGEX MATCHALL "always_ff" registers "${source}")
    list(LENGTH registers register_count)
    set(expected_register_blocks 1)
    if(BLOCK_RAM)
        set(expected_register_blocks 2) # Scheduler and the reusable byte RAM module.
    endif()
    if(NOT register_count EQUAL expected_register_blocks)
        message(FATAL_ERROR "Combinational process partitioning must not add register stages in ${module}")
    endif()
    string(REGEX MATCH "function static [^\n]+ hls_[A-Za-z0-9_]+__shared_[0-9]+" first_body "${source}")
    if(NOT first_body)
        message(FATAL_ERROR "Missing shared scheduled functions in ${module}")
    endif()
    string(FIND "${source}" "${first_body}" body_start)
    string(FIND "${source}" "always_comb" body_end)
    math(EXPR body_size "${body_end} - ${body_start}")
    string(SUBSTRING "${source}" ${body_start} ${body_size} bodies)
    if(bodies MATCHES "storage\\[")
        message(FATAL_ERROR "Scheduled method still expands raw byte accesses in ${module}")
    endif()
    string(APPEND rtl "${source}\n")
endforeach()
set(top "${stem}Top")
if(NOT rtl MATCHES "// loop boundary")
    message(FATAL_ERROR "Expected loop continuations")
endif()
if(stem STREQUAL "DelayedRbMap")
    foreach(method rotate fix_insert fix_erase find insert_or_assign erase clear next)
        if(NOT rtl MATCHES "// instantiated: [^\n]*RbMap[^\n]*::${method}" OR
           NOT rtl MATCHES "function static [^\n]+ hls_RbMap__${method}__shared_[0-9]+")
            message(FATAL_ERROR "Missing small red-black tree method: ${method}")
        endif()
    endforeach()
    if(rtl MATCHES "// instantiated: std::.*(__tree|_Rb_tree)")
        message(FATAL_ERROR "Small-map RTL must use its own tree, not the std::map reference")
    endif()
elseif(NOT stem STREQUAL "DelayedSharing" AND NOT stem STREQUAL "DelayedMemoryEffects" AND NOT rtl MATCHES "// instantiated: std::")
    message(FATAL_ERROR "Expected instantiated standard-library methods")
endif()
string(REGEX REPLACE "//[^\n]*" "" named_rtl "${rtl}")
if(stem STREQUAL "DelayedAggregates")
    if(named_rtl MATCHES "hls_storage_(read|load|write)_" OR NOT named_rtl MATCHES "localparam int MEM_BYTES = 16;")
        message(FATAL_ERROR "Known struct temporaries, fields, and references must not use byte storage")
    endif()
    if(NOT named_rtl MATCHES "values_reg[.]hls_object__object_" OR
       NOT named_rtl MATCHES "values_reg[.]hls_AggregatesMethods__command__call_[0-9]+_depth_1__temporary_")
        message(FATAL_ERROR "Persistent state and the loop's live aggregate must retain registers")
    endif()
endif()
if(named_rtl MATCHES "__this_addr_|(^|[^A-Za-z0-9_])pc_reg([^A-Za-z0-9_]|$)|@hls_access_")
    message(FATAL_ERROR "Unresolved source access or indirect this/program counter lowering")
endif()
if(stem STREQUAL "DelayedBindings")
    if(NOT named_rtl MATCHES "values_reg\\.hls_BindingsCounter__repeat__call_[0-9]+_depth_1__i_[0-9]+")
        message(FATAL_ERROR "Loop index must remain live across the repeated method's clocks")
    endif()
    if(named_rtl MATCHES "localparam[^\n]+__(selected|amount)_addr_")
        message(FATAL_ERROR "Direct pointer/reference bindings must not allocate parameter memory")
    endif()
endif()
if(NOT rtl MATCHES "// Source values: ([0-9]+) direct [a-z]+, ([0-9]+) live across clocks")
    message(FATAL_ERROR "Missing direct source variable lowering")
endif()
if(NOT CMAKE_MATCH_2 LESS CMAKE_MATCH_1)
    message(FATAL_ERROR "Not every temporary needs a register")
endif()
if(named_rtl MATCHES "(^|[^A-Za-z0-9_])(automatic|ref|inout)([^A-Za-z0-9_]|$)")
    message(FATAL_ERROR "Clocked RTL must use static value-returning functions, not automatic/ref/inout")
endif()
if(named_rtl MATCHES "function static void step_[0-9]" OR named_rtl MATCHES "scratch\\.t[0-9]+")
    message(FATAL_ERROR "Source method/variable names were replaced with anonymous numbering")
endif()
if(NOT named_rtl MATCHES "function static [^\n]+ hls_[A-Za-z0-9_]+__command__shared_[0-9]+")
    message(FATAL_ERROR "Missing executable source-named command function")
endif()
if(stem STREQUAL "DelayedArray" OR stem STREQUAL "DelayedVector")
    foreach(variable bias value i)
        if(NOT named_rtl MATCHES "logic \\[[0-9]+:0\\] values__hls_[A-Za-z0-9_]+__sum__call_[0-9]+_depth_1__${variable}_[0-9]+;")
            message(FATAL_ERROR "Missing direct named sum parameter/local: ${variable}")
        endif()
        if(named_rtl MATCHES "localparam[^\n]+__sum__call_[0-9]+_depth_1__${variable}_addr_")
            message(FATAL_ERROR "Unaddressed scalar ${variable} must not be allocated in memory")
        endif()
    endforeach()
endif()
if(stem STREQUAL "DelayedVector")
    foreach(field __begin_ __end_ __cap_)
        if(NOT rtl MATCHES "// field: [^\n]*${field} byte offset")
            message(FATAL_ERROR "Expected the actual libc++ vector field ${field}")
        endif()
    endforeach()
endif()
if(stem STREQUAL "DelayedOverrides")
    foreach(replacement absent_rtl integer_rtl overload32_rtl overload64_rtl)
        if(NOT rtl MATCHES "// instantiated: override [^\n]+ -> ${replacement}" OR
           NOT named_rtl MATCHES "function static [^\n]+ hls_${replacement}__shared_")
            message(FATAL_ERROR "Missing executable HLS override: ${replacement}")
        endif()
    endforeach()
endif()
if(stem STREQUAL "DelayedUnorderedMap")
    foreach(helper __emplace_unique_key_args __do_rehash)
        if(NOT named_rtl MATCHES "function static [^\n]+ hls_[A-Za-z0-9_]*${helper}__shared_")
            message(FATAL_ERROR "Missing actual hash-table algorithm: ${helper}")
        endif()
    endforeach()
    if(NOT rtl MATCHES "// instantiated: override std::[A-Za-z0-9_:]*__next_prime -> unordered_map_rtl::next_prime")
        message(FATAL_ERROR "Missing explicit test-local prime replacement")
    endif()
endif()
if(stem STREQUAL "DelayedList")
    foreach(helper __link_nodes_at_back __unlink_nodes __delete_node)
        if(NOT rtl MATCHES "// instantiated: [^\n]*${helper}" OR
           NOT named_rtl MATCHES "function static [^\n]+ hls_[A-Za-z0-9_]*${helper}__shared_[0-9]+")
            message(FATAL_ERROR "Missing actual list algorithm: ${helper}")
        endif()
    endforeach()
    foreach(field __prev_ __next_)
        if(NOT named_rtl MATCHES "\\+ hls_field_[A-Za-z0-9_]*${field}_offset_[0-9]+")
            message(FATAL_ERROR "Missing actual list link access: ${field}")
        endif()
    endforeach()
endif()
if(stem STREQUAL "DelayedMap" OR stem STREQUAL "DelayedMultimap")
    if(SHARED_MEMORY)
        string(REGEX MATCHALL "// Recursive body: [A-Za-z0-9_]+__destroy depth [0-9]+, [0-9]+ callers" destroy_bodies "${rtl}")
        list(LENGTH destroy_bodies destroy_count)
        if(NOT destroy_count EQUAL 8)
            message(FATAL_ERROR "Tree destruction must reuse eight depth-specific bodies, got ${destroy_count}")
        endif()
        foreach(rotation __tree_left_rotate __tree_right_rotate)
            if(NOT rtl MATCHES "// Shared clocked body: [A-Za-z0-9_]+${rotation} depth 1, ([2-9]|[1-9][0-9]+) callers")
                message(FATAL_ERROR "Tree rotation must share its schedule and live values across callers: ${rotation}")
            endif()
            if(rtl MATCHES "${rotation}__call_[0-9]+_depth_1")
                message(FATAL_ERROR "Tree rotation still contains per-call state: ${rotation}")
            endif()
        endforeach()
    endif()
    if(rtl MATCHES "_Rb_tree|tree\\.cc")
        message(FATAL_ERROR "Map must use libc++ header algorithms, not bundled libstdc++ sources")
    endif()
    foreach(helper __tree_min __tree_next_iter __tree_balance_after_insert __tree_remove __tree_left_rotate __tree_right_rotate destroy)
        if(NOT rtl MATCHES "// instantiated: [^\n]*${helper}")
            message(FATAL_ERROR "Missing actual tree algorithm: ${helper}")
        endif()
        if(NOT named_rtl MATCHES "function static [^\n]+ hls_[A-Za-z0-9_]*${helper}__shared_[0-9]+")
            message(FATAL_ERROR "Tree method name exists only in comments: ${helper}")
        endif()
    endforeach()
    foreach(field __left_ __right_ __parent_ __is_black_)
        if(NOT rtl MATCHES "// field: [^\n]*${field}")
            message(FATAL_ERROR "Missing actual tree node field: ${field}")
        endif()
        if(NOT named_rtl MATCHES "\\+ hls_field_[A-Za-z0-9_]*${field}_offset_[0-9]+")
            message(FATAL_ERROR "Tree field name is missing from actual address calculation: ${field}")
        endif()
    endforeach()
endif()
if(stem STREQUAL "DelayedReuse")
    set(whole_methods _S_left inspect)
    if(SHARED_MEMORY)
        # These methods dereference heap nodes; a shared port deliberately
        # gives their memory accesses clocked continuations.
        set(whole_methods)
    endif()
    foreach(method IN LISTS whole_methods)
        string(REGEX MATCHALL "function static [^\n]+ hls_ReuseNode__${method}__shared_[0-9]+" definitions "${named_rtl}")
        list(LENGTH definitions count)
        if(NOT count EQUAL 1)
            message(FATAL_ERROR "Expected one complete ${method} function, not call/return fragments: ${count}")
        endif()
        string(FIND "${named_rtl}" "${definitions}" start)
        string(SUBSTRING "${named_rtl}" ${start} -1 rest)
        string(FIND "${rest}" "endfunction" end)
        string(SUBSTRING "${rest}" 0 ${end} body)
        if(body MATCHES "active|next_block|else_block|phase")
            message(FATAL_ERROR "Non-suspending method ${method} must not contain scheduler controls")
        endif()
        if(NOT body MATCHES "if \\(")
            message(FATAL_ERROR "Missing structured branch in ${method}")
        endif()
    endforeach()
    if(named_rtl MATCHES "function static [^\n]+ hls_ReuseNode___M_node_ptr__shared_")
        message(FATAL_ERROR "return this must not produce a standalone identity-copy function")
    endif()
    set(helper_widths 8 16 24 32 64 128)
    if(SHARED_MEMORY)
        set(helper_widths)
    endif()
    foreach(width IN LISTS helper_widths)
        foreach(operation read)
            string(REGEX MATCHALL "function static [^\n]+ hls_storage_${operation}_${width}\\(" helpers "${named_rtl}")
            list(LENGTH helpers count)
            if(NOT count EQUAL 1)
                message(FATAL_ERROR "Expected one shared ${width}-bit storage ${operation} helper, got ${count}")
            endif()
        endforeach()
        foreach(bank RANGE 0 7)
            string(REGEX MATCHALL "function static bank_t hls_bank_write_${width}_${bank}\\(" helpers "${named_rtl}")
            list(LENGTH helpers count)
            if(NOT count EQUAL 1)
                message(FATAL_ERROR "Expected one ${width}-bit writer for lane ${bank}")
            endif()
        endforeach()
    endforeach()
    set(reused_methods mix widen)
    if(SHARED_MEMORY)
        set(reused_methods widen)
    endif()
    foreach(method IN LISTS reused_methods)
        string(REGEX MATCHALL "function static [^\n]+ hls_ReuseMethods__${method}__shared_[0-9]+" definitions "${named_rtl}")
        list(LENGTH definitions count)
        set(expected 1)
        if(method STREQUAL "widen")
            set(expected 2)
        endif()
        if(NOT count EQUAL expected)
            message(FATAL_ERROR "Expected ${expected} ${method} bodies, got ${count}")
        endif()
    endforeach()
    if(NOT named_rtl MATCHES "input logic \\[32-1:0\\] p_[A-Za-z0-9_]+" OR
       NOT named_rtl MATCHES "input logic \\[64-1:0\\] p_[A-Za-z0-9_]+_addr_[0-9]+")
        message(FATAL_ERROR "Shared bodies must parameterize values and source object addresses")
    endif()
endif()
file(GLOB ir "${WORK}/generated/*.ll")
if(ir)
    message(FATAL_ERROR "AST scheduling must not produce LLVM IR")
endif()
execute_process(COMMAND "${CXX}" -print-file-name=libatomic.so OUTPUT_VARIABLE atomic OUTPUT_STRIP_TRAILING_WHITESPACE)
get_filename_component(atomic_dir "${atomic}" DIRECTORY)
file(GLOB packages "${WORK}/generated/*_pkg.sv")
# Preserve shared method bodies during host model compilation.
set(verilator_options -fno-inline-funcs)
list(JOIN HLS_CXX_FLAGS " " cxx_flags)
list(JOIN HLS_LINK_FLAGS " " link_flags)
execute_process(COMMAND "${VERILATOR}" --cc --exe --top-module "${top}" --prefix VDelayedModel
    --Mdir "${WORK}/obj_dir" -Wno-fatal ${verilator_options}
    -CFLAGS "${cxx_flags} -I${ROOT}/include -DVERILATOR"
    -LDFLAGS "${link_flags} -L${atomic_dir}"
    ${packages} ${generated} "${WORK}/generated/${top}.sv" "${SOURCE}"
    RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
file(WRITE "${WORK}/verilator.log" "${output}\n${error}")
if(NOT result EQUAL 0)
    message(FATAL_ERROR "Verilator failed:\n${output}\n${error}")
endif()
if(error MATCHES "Warning-(MULTIDRIVEN|LATCH)")
    message(FATAL_ERROR "Scheduled RTL must not introduce multiple drivers or latches:\n${error}")
endif()
execute_process(COMMAND "${MAKE}" -C "${WORK}/obj_dir" -f VDelayedModel.mk -j2 "CXX=${CXX}" "LINK=${CXX}"
    RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
file(WRITE "${WORK}/build.log" "${output}\n${error}")
if(NOT result EQUAL 0)
    message(FATAL_ERROR "Build failed:\n${output}\n${error}")
endif()
execute_process(COMMAND "${WORK}/obj_dir/VDelayedModel"
    RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
file(WRITE "${WORK}/simulation.log" "${output}\n${error}")
if(NOT result EQUAL 0)
    message(FATAL_ERROR "Simulation failed:\n${output}\n${error}")
endif()
message(STATUS "${output}")
if(stem STREQUAL "DelayedReuse" AND NOT SHARED_MEMORY)
    include("${CMAKE_CURRENT_LIST_DIR}/StorageHelpers.cmake")
endif()
