include("${TOOLCHAIN}")
file(REMOVE_RECURSE "${WORK}")
file(MAKE_DIRECTORY "${WORK}/generated")
separate_arguments(definitions UNIX_COMMAND "${DEFINITIONS}")
list(JOIN HLS_CXX_FLAGS " " cflags)
string(APPEND cflags " -I${ROOT}/include -DVERILATOR")
set(parse_definitions)
execute_process(COMMAND "${CXX}" -print-file-name=libatomic.so
    OUTPUT_VARIABLE atomic_library OUTPUT_STRIP_TRAILING_WHITESPACE)
list(JOIN HLS_LINK_FLAGS " " hls_link_flags)
set(link_flags -LDFLAGS "${hls_link_flags}")
if(IS_ABSOLUTE "${atomic_library}" AND EXISTS "${atomic_library}")
    get_filename_component(atomic_directory "${atomic_library}" DIRECTORY)
    list(APPEND link_flags -LDFLAGS "-L${atomic_directory}")
endif()
foreach(definition IN LISTS definitions)
    list(APPEND parse_definitions "-D${definition}")
    string(APPEND cflags " -D${definition}")
endforeach()
set(hls_options --hls)
if(TOP STREQUAL "StaticHelper")
    set(hls_options)
endif()
execute_process(COMMAND "${CPPHDL}" ${hls_options} --generated-dir "${WORK}/generated"
    "${SOURCE}" -- "-I${ROOT}/include" ${parse_definitions} ${HLS_PARSE_FLAGS}
    RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
file(WRITE "${WORK}/conversion.log" "${output}\n${error}")
if(NOT result EQUAL 0)
    message(FATAL_ERROR "HLS conversion failed:\n${output}\n${error}")
endif()
file(GLOB packages "${WORK}/generated/*_pkg.sv")
file(GLOB rtl "${WORK}/generated/*.sv")
list(REMOVE_ITEM rtl ${packages})
foreach(file IN LISTS rtl packages)
    file(READ "${file}" text)
    if(text MATCHES "unknown:|RecoveryExpr|function automatic")
        message(FATAL_ERROR "Invalid or automatic function in ${file}")
    endif()
endforeach()
if(TOP STREQUAL "SramTop")
    file(READ "${WORK}/generated/HlsSram.sv" memory_rtl)
    if(NOT memory_rtl MATCHES "words\\[CAPACITY\\]")
        message(FATAL_ERROR "Expected memory<> to lower to unpacked SRAM words")
    endif()
endif()
if(TOP STREQUAL "Recursion")
    file(READ "${WORK}/generated/Recursion.sv" text)
    foreach(depth RANGE 0 3)
        if(NOT text MATCHES "function[^\n]*sum_hls_${depth} ")
            message(FATAL_ERROR "Missing unfolded function ${depth}")
        endif()
    endforeach()
    if(NOT text MATCHES "default_sum_hls_9" OR NOT text MATCHES "odd_hls_3" OR
       NOT text MATCHES "even_hls_3" OR NOT text MATCHES "walk_hls_3")
        message(FATAL_ERROR "Default, mutual, or helper recursion was not unfolded")
    endif()
endif()
execute_process(COMMAND "${VERILATOR}" --cc --exe --top-module "${TOP}"
    -Wno-fatal --Mdir "${WORK}/obj_dir" -CFLAGS "${cflags}" ${link_flags}
    ${packages} ${rtl} "${SOURCE}"
    RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
file(WRITE "${WORK}/verilator.log" "${output}\n${error}")
if(NOT result EQUAL 0)
    message(FATAL_ERROR "Verilator failed:\n${output}\n${error}")
endif()
execute_process(COMMAND "${MAKE}" -C "${WORK}/obj_dir" -f "V${TOP}.mk" -j2
    "CXX=${CXX}" "LINK=${CXX}"
    RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
file(WRITE "${WORK}/build.log" "${output}\n${error}")
if(NOT result EQUAL 0)
    message(FATAL_ERROR "RTL simulation build failed:\n${output}\n${error}")
endif()
execute_process(COMMAND "${WORK}/obj_dir/V${TOP}"
    RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
if(NOT result EQUAL 0)
    message(FATAL_ERROR "RTL mismatch:\n${output}\n${error}")
endif()
message(STATUS "${output}")
