

//#define ENABLE_RV32IA  // atomics
//#define ENABLE_ZICSR   // CSR

#define L1_CACHE_SIZE 1024
#define L2_CACHE_SIZE 8192
#define L1_CACHE_ASSOCIATIONS 2
#define L2_CACHE_ASSOCIATIONS 4

#define BRANCH_PREDICTOR_ENTRIES 16
#define BRANCH_PREDICTOR_COUNTER_BITS 2
