set(work "${GENERATED_DIR}/${CASE}")
file(REMOVE_RECURSE "${work}")
file(MAKE_DIRECTORY "${work}")
set(defines -DFLOW_XXX)
set(lanes 0)
set(sum 1)
set(mul 1)
if(CASE STREQUAL "concrete")
    list(APPEND defines -DCONCRETE_VALUES)
    set(lanes 8)
    set(sum 2)
    set(mul 3)
elseif(CASE STREQUAL "partial")
    list(APPEND defines -DPARTIAL_VALUES)
    set(lanes 8)
elseif(CASE STREQUAL "expressions")
    list(APPEND defines -DDEFAULT_EXPRESSIONS)
    set(lanes 5)
    set(sum 2)
    set(mul -1)
elseif(CASE STREQUAL "named" OR CASE STREQUAL "parent")
    if(CASE STREQUAL "named")
        list(APPEND defines -DNAMED_VALUES)
    else()
        list(APPEND defines -DPARENT_TEMPLATE)
    endif()
    set(lanes 12)
    set(sum 4)
    set(mul 6)
elseif(NOT CASE STREQUAL "standalone")
    message(FATAL_ERROR "Unknown replacement defaults case: ${CASE}")
endif()

execute_process(COMMAND "${CPPHDL}" "--generated-dir=${work}"
    "${SOURCE_ROOT}/tests/format/ReplacementDefaults.h" -- ${defines}
    RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
if(NOT result EQUAL 0)
    message(FATAL_ERROR "Replacement conversion failed:\n${output}\n${error}")
endif()
if(NOT EXISTS "${work}/Arithmetic.sv")
    message(FATAL_ERROR "Arithmetic.sv was not generated:\n${output}\n${error}")
endif()
file(READ "${work}/Arithmetic.sv" rtl)
string(FIND "${rtl}" "$(" placeholder)
if(NOT placeholder EQUAL -1)
    message(FATAL_ERROR "Unsubstituted replacement parameter:\n${rtl}")
endif()
foreach(name LANES PIPE_DEPTH_SUM PIPE_DEPTH_MUL)
    if(name STREQUAL "LANES")
        set(value ${lanes})
    elseif(name STREQUAL "PIPE_DEPTH_SUM")
        set(value ${sum})
    else()
        set(value ${mul})
    endif()
    string(FIND "${rtl}" "parameter int ${name} = ${value}" found)
    if(found EQUAL -1)
        message(FATAL_ERROR "Wrong replacement value for ${name}:\n${rtl}")
    endif()
endforeach()
foreach(expected "REPLACEMENT_DEFAULTS_${lanes}_${sum}_${mul}"
                 "Literal dollar: $; SV system function: $bits(value_out)")
    string(FIND "${rtl}" "${expected}" found)
    if(found EQUAL -1)
        message(FATAL_ERROR "Replacement text was changed incorrectly: ${expected}\n${rtl}")
    endif()
endforeach()

if(VERILATOR)
    set(top Arithmetic)
    if(CASE STREQUAL "named" OR CASE STREQUAL "parent")
        set(top ArithmeticTop)
    endif()
    file(GLOB sources "${work}/*.sv")
    list(REMOVE_ITEM sources "${work}/Predef_pkg.sv")
    execute_process(COMMAND "${VERILATOR}" --lint-only --Wno-fatal
        --top-module ${top} "${work}/Predef_pkg.sv" ${sources}
        RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
    if(NOT result EQUAL 0)
        message(FATAL_ERROR "Replacement RTL failed lint:\n${output}\n${error}")
    endif()
    if(CASE STREQUAL "parent")
        execute_process(COMMAND "${VERILATOR}" --cc --exe --main --timing --Wno-fatal
            -CFLAGS "-std=c++20"
            --top-module ReplacementParameterCheck --Mdir "${work}/obj_dir"
            "${work}/Predef_pkg.sv" ${sources}
            "${SOURCE_ROOT}/tests/format/ReplacementParameterCheck.sv"
            RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
        if(NOT result EQUAL 0)
            message(FATAL_ERROR "Override simulation generation failed:\n${output}\n${error}")
        endif()
        set(link "${CXX}")
        if(CONDA_PREFIX)
            string(APPEND link " -L${CONDA_PREFIX}/lib -static-libstdc++ -static-libgcc")
        endif()
        execute_process(COMMAND "${MAKE}" -C "${work}/obj_dir" -j2
            -f VReplacementParameterCheck.mk "CXX=${CXX}" "LINK=${link}"
            RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
        if(NOT result EQUAL 0)
            message(FATAL_ERROR "Override simulation build failed:\n${output}\n${error}")
        endif()
        execute_process(COMMAND "${work}/obj_dir/VReplacementParameterCheck"
            RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
        if(NOT result EQUAL 0)
            message(FATAL_ERROR "Override simulation failed:\n${output}\n${error}")
        endif()
    endif()
endif()
