set(source "${TEST_DIR}/MissedCalls.h")
set(expected_count 0)
set(expected_calls)
set(args)
set(defines)
if(CASE STREQUAL "deferred_template")
    set(source "${TEST_DIR}/DeferredLifecycle.h")
elseif(CASE STREQUAL "empty" OR CASE STREQUAL "missing_effectful")
    set(source "${TEST_DIR}/EmptyLifecycle.h")
    if(CASE STREQUAL "missing_effectful")
        list(APPEND defines -DMISSING_EFFECTFUL)
        list(APPEND expected_calls
            "Missing child work: working._work()"
            "Missing child strobe: committing._strobe()")
    endif()
elseif(CASE STREQUAL "assign_ports")
    set(source "${TEST_DIR}/../code/AssignPorts.cpp")
elseif(CASE STREQUAL "constexpr_ports")
    set(source "${TEST_DIR}/../code/ConstexprPortSize.cpp")
elseif(CASE STREQUAL "tuple_pipeline")
    set(source "${TEST_DIR}/../../examples/tuple/RiscV.cpp")
elseif(CASE STREQUAL "register")
    list(APPEND defines -DMISSING_REGISTER)
    list(APPEND expected_calls "Missing register strobe: value.strobe()")
elseif(CASE STREQUAL "memory")
    list(APPEND defines -DMISSING_MEMORY)
    list(APPEND expected_calls "Missing memory apply: storage.apply()")
elseif(CASE STREQUAL "child_work")
    list(APPEND defines -DMISSING_CHILD_WORK)
    list(APPEND expected_calls "Missing child work: child._work()")
elseif(CASE STREQUAL "child_strobe")
    list(APPEND defines -DMISSING_CHILD_STROBE)
    list(APPEND expected_calls "Missing child strobe: child._strobe()")
elseif(CASE STREQUAL "work_method")
    list(APPEND defines -DMISSING_WORK_METHOD)
    list(APPEND expected_calls "Missing child work: child._work()")
elseif(CASE STREQUAL "strobe_method")
    list(APPEND defines -DMISSING_STROBE_METHOD)
    list(APPEND expected_calls
        "Missing register strobe: value.strobe()"
        "Missing memory apply: storage.apply()"
        "Missing child strobe: child._strobe()")
elseif(CASE STREQUAL "wrong_phase" OR CASE STREQUAL "dead_helper")
    string(TOUPPER "${CASE}" define)
    list(APPEND defines "-D${define}")
    list(APPEND expected_calls
        "Missing register strobe: value.strobe()"
        "Missing memory apply: storage.apply()"
        "Missing child work: child._work()"
        "Missing child strobe: child._strobe()")
elseif(CASE STREQUAL "inheritance" OR CASE STREQUAL "hidden_base")
    set(source "${TEST_DIR}/ValidLifecycle.h")
    if(CASE STREQUAL "hidden_base")
        list(APPEND defines -DHIDDEN_BASE)
        list(APPEND expected_calls "Missing register strobe: values.strobe()")
    endif()
elseif(CASE STREQUAL "named" OR CASE STREQUAL "missing_named")
    set(source "${TEST_DIR}/NamedLifecycle.h")
    list(APPEND args --primary_clock fast_clk 100000000 --secondary_clock slow_clk 40000000)
    if(CASE STREQUAL "missing_named")
        list(APPEND defines -DMISSING_NAMED)
        list(APPEND expected_calls
            "Missing child work: child._work_slow_clk()"
            "Missing child strobe: child._strobe_slow_clk()")
    endif()
elseif(NOT CASE STREQUAL "valid")
    message(FATAL_ERROR "Unknown lifecycle case: ${CASE}")
endif()

execute_process(
    COMMAND "${CPPHDL}" --generated-dir "${GENERATED_DIR}/${CASE}"
        ${args} "${source}" -- "-I${INCLUDE_DIR}" ${defines}
    RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
set(diagnostic "${output}${error}")
if(NOT result EQUAL 0)
    message(FATAL_ERROR "Conversion failed for ${CASE}:\n${diagnostic}")
endif()

list(LENGTH expected_calls expected_count)
string(REGEX MATCHALL "MISSED CALL FOUND" banners "${diagnostic}")
list(LENGTH banners count)
if(NOT count EQUAL expected_count)
    message(FATAL_ERROR "Expected ${expected_count} banners, got ${count}:\n${diagnostic}")
endif()
foreach(call IN LISTS expected_calls)
    string(FIND "${diagnostic}" "${call}" found)
    if(found LESS 0)
        message(FATAL_ERROR "Missing diagnostic '${call}':\n${diagnostic}")
    endif()
endforeach()

# Each warning must be exactly four lines, with the requested banner heading.
string(REGEX MATCHALL
    "/\\*\\*+ MISSED CALL FOUND \\*+/\n/\\* WARNING:[^\n]*\n/\\* Missing [^\n]*\n/\\*\\*+/"
    complete_banners "${diagnostic}")
list(LENGTH complete_banners complete_count)
if(NOT complete_count EQUAL count)
    message(FATAL_ERROR "Malformed four-line banner:\n${diagnostic}")
endif()
foreach(banner IN LISTS complete_banners)
    string(REPLACE "\n" ";" lines "${banner}")
    list(GET lines 0 heading)
    string(LENGTH "${heading}" width)
    foreach(line IN LISTS lines)
        string(LENGTH "${line}" line_width)
        if(NOT line_width EQUAL width OR NOT line MATCHES "^/\\*.*\\*/$")
            message(FATAL_ERROR "Banner is not a complete rectangle:\n${banner}")
        endif()
        if(line MATCHES "^/\\* (WARNING:|Missing )" AND NOT line MATCHES " \\*+/$")
            message(FATAL_ERROR "Banner text lacks asterisk padding:\n${banner}")
        endif()
    endforeach()
endforeach()
