auto pow2 = [](unsigned x) constexpr { return 1u << x; };
bool IS_XLEN32 = CVA6Cfg.XLEN == 32;
bool IS_XLEN64 = CVA6Cfg.XLEN != 32;
bool FpPresent = (bool)CVA6Cfg.RVF || (bool)CVA6Cfg.RVD || (bool)CVA6Cfg.XF16 || (bool)CVA6Cfg.XF16ALT || (bool)CVA6Cfg.XF8;
bool NSX = (bool)CVA6Cfg.XF16 || (bool)CVA6Cfg.XF16ALT || (bool)CVA6Cfg.XF8 || (bool)CVA6Cfg.XFVec;
unsigned FLen = (bool)CVA6Cfg.RVD ? 64 : (bool)CVA6Cfg.RVF ? 32 : (bool)CVA6Cfg.XF16 ? 16 : (bool)CVA6Cfg.XF16ALT ? 16 : (bool)CVA6Cfg.XF8 ? 8 : 1;
bool RVFVec = (bool)CVA6Cfg.RVF && (bool)CVA6Cfg.XFVec && (FLen > 32);
bool XF16Vec = (bool)CVA6Cfg.XF16 && (bool)CVA6Cfg.XFVec && (FLen > 16);
bool XF16ALTVec = (bool)CVA6Cfg.XF16ALT && (bool)CVA6Cfg.XFVec && (FLen > 16);
bool XF8Vec = (bool)CVA6Cfg.XF8 && (bool)CVA6Cfg.XFVec && (FLen > 8);
bool EnableAccelerator = static_cast<bool>(CVA6Cfg.RVV);
unsigned NrWbPorts = (CVA6Cfg.CvxifEn || EnableAccelerator) ? 5 : 4;
unsigned ICACHE_INDEX_WIDTH = clog2(CVA6Cfg.IcacheByteSize / CVA6Cfg.IcacheSetAssoc);
unsigned DCACHE_INDEX_WIDTH = clog2(CVA6Cfg.DcacheByteSize / CVA6Cfg.DcacheSetAssoc);
unsigned DCACHE_OFFSET_WIDTH = clog2(CVA6Cfg.DcacheLineWidth / 8);
unsigned VpnLen = (CVA6Cfg.XLEN == 64) ? (CVA6Cfg.RVH ? 29 : 27) : 20;
unsigned PtLevels = (CVA6Cfg.XLEN == 64) ? 3 : 2;
unsigned PLEN_v = (CVA6Cfg.XLEN == 32) ? 34 : 56;
unsigned GPLEN_v = (CVA6Cfg.XLEN == 32) ? 34 : 41;
unsigned ASID_WIDTH_v = (CVA6Cfg.XLEN == 64) ? 16 : 1;
unsigned VMID_WIDTH_v = (CVA6Cfg.XLEN == 64) ? 14 : 1;
unsigned ICACHE_USER_LINE_WIDTH_v = (CVA6Cfg.AxiUserWidth == 1) ? 4 : CVA6Cfg.IcacheLineWidth;
unsigned DCACHE_USER_LINE_WIDTH_v = (CVA6Cfg.AxiUserWidth == 1) ? 4 : CVA6Cfg.DcacheLineWidth;
unsigned AXI_USER_EN_v = (CVA6Cfg.DataUserEn | CVA6Cfg.FetchUserEn) != 0;
unsigned ModeW_v = (CVA6Cfg.XLEN == 32) ? 1 : 4;
unsigned ASIDW_v = (CVA6Cfg.XLEN == 32) ? 9 : 16;
unsigned VMIDW_v = (CVA6Cfg.XLEN == 32) ? 7 : 14;
unsigned PPNW_v = (CVA6Cfg.XLEN == 32) ? 22 : 44;
unsigned GPPNW_v = (CVA6Cfg.XLEN == 32) ? 22 : 29;
auto MODE_SV_v = (CVA6Cfg.XLEN == 32) ? config_pkg::ModeSv32 : config_pkg::ModeSv39;
unsigned SV_v = (MODE_SV_v == config_pkg::ModeSv32) ? 32 : 39;
unsigned SVX_v = (MODE_SV_v == config_pkg::ModeSv32) ? 34 : 41;
config_pkg::cva6_cfg_t cfg{};
sv_assign_field(cfg.XLEN, CVA6Cfg.XLEN);
sv_assign_field(cfg.VLEN, CVA6Cfg.VLEN);
sv_assign_field(cfg.PLEN, PLEN_v);
sv_assign_field(cfg.GPLEN, GPLEN_v);
sv_assign_field(cfg.IS_XLEN32, IS_XLEN32);
sv_assign_field(cfg.IS_XLEN64, IS_XLEN64);
sv_assign_field(cfg.XLEN_ALIGN_BYTES, clog2(CVA6Cfg.XLEN / 8));
sv_assign_field(cfg.ASID_WIDTH, ASID_WIDTH_v);
sv_assign_field(cfg.VMID_WIDTH, VMID_WIDTH_v);
sv_assign_field(cfg.FpgaEn, CVA6Cfg.FpgaEn);
sv_assign_field(cfg.FpgaAlteraEn, CVA6Cfg.FpgaAlteraEn);
sv_assign_field(cfg.TechnoCut, CVA6Cfg.TechnoCut);
sv_assign_field(cfg.SuperscalarEn, CVA6Cfg.SuperscalarEn);
sv_assign_field(cfg.NrCommitPorts, CVA6Cfg.SuperscalarEn ? 2 : CVA6Cfg.NrCommitPorts);
sv_assign_field(cfg.NrIssuePorts, CVA6Cfg.SuperscalarEn ? 2 : 1);
sv_assign_field(cfg.SpeculativeSb, CVA6Cfg.SuperscalarEn);
sv_assign_field(cfg.NrALUs, CVA6Cfg.SuperscalarEn ? 2 : 1);
sv_assign_field(cfg.ALUBypass, CVA6Cfg.SuperscalarEn ? (bool)CVA6Cfg.ALUBypass : false);
sv_assign_field(cfg.NrLoadPipeRegs, CVA6Cfg.NrLoadPipeRegs);
sv_assign_field(cfg.NrStorePipeRegs, CVA6Cfg.NrStorePipeRegs);
sv_assign_field(cfg.AxiAddrWidth, CVA6Cfg.AxiAddrWidth);
sv_assign_field(cfg.AxiDataWidth, CVA6Cfg.AxiDataWidth);
sv_assign_field(cfg.AxiIdWidth, CVA6Cfg.AxiIdWidth);
sv_assign_field(cfg.AxiUserWidth, CVA6Cfg.AxiUserWidth);
sv_assign_field(cfg.MEM_TID_WIDTH, CVA6Cfg.MemTidWidth);
sv_assign_field(cfg.NrLoadBufEntries, CVA6Cfg.NrLoadBufEntries);
sv_assign_field(cfg.RVF, CVA6Cfg.RVF);
sv_assign_field(cfg.RVD, CVA6Cfg.RVD);
sv_assign_field(cfg.XF16, CVA6Cfg.XF16);
sv_assign_field(cfg.XF16ALT, CVA6Cfg.XF16ALT);
sv_assign_field(cfg.XF8, CVA6Cfg.XF8);
sv_assign_field(cfg.RVA, CVA6Cfg.RVA);
sv_assign_field(cfg.RVB, CVA6Cfg.RVB);
sv_assign_field(cfg.ZKN, CVA6Cfg.ZKN);
sv_assign_field(cfg.RVV, CVA6Cfg.RVV);
sv_assign_field(cfg.RVC, CVA6Cfg.RVC);
sv_assign_field(cfg.RVH, CVA6Cfg.RVH);
sv_assign_field(cfg.RVZCB, CVA6Cfg.RVZCB);
sv_assign_field(cfg.RVZCMT, CVA6Cfg.RVZCMT);
sv_assign_field(cfg.RVZCMP, CVA6Cfg.RVZCMP);
sv_assign_field(cfg.XFVec, CVA6Cfg.XFVec);
sv_assign_field(cfg.CvxifEn, CVA6Cfg.CvxifEn);
sv_assign_field(cfg.CoproType, CVA6Cfg.CoproType);
sv_assign_field(cfg.RVZiCond, CVA6Cfg.RVZiCond);
sv_assign_field(cfg.RVZiCbom, CVA6Cfg.RVZiCbom);
sv_assign_field(cfg.RVZicntr, CVA6Cfg.RVZicntr);
sv_assign_field(cfg.RVZihpm, CVA6Cfg.RVZihpm);
sv_assign_field(cfg.NR_SB_ENTRIES, CVA6Cfg.NrScoreboardEntries);
sv_assign_field(cfg.TRANS_ID_BITS, clog2(CVA6Cfg.NrScoreboardEntries));
sv_assign_field(cfg.FpPresent, FpPresent);
sv_assign_field(cfg.NSX, NSX);
sv_assign_field(cfg.FLen, FLen);
sv_assign_field(cfg.RVFVec, RVFVec);
sv_assign_field(cfg.XF16Vec, XF16Vec);
sv_assign_field(cfg.XF16ALTVec, XF16ALTVec);
sv_assign_field(cfg.XF8Vec, XF8Vec);
sv_assign_field(cfg.NrRgprPorts, CVA6Cfg.SuperscalarEn ? 4 : 2);
sv_assign_field(cfg.NrWbPorts, NrWbPorts);
sv_assign_field(cfg.EnableAccelerator, EnableAccelerator);
sv_assign_field(cfg.PerfCounterEn, CVA6Cfg.PerfCounterEn);
sv_assign_field(cfg.MmuPresent, CVA6Cfg.MmuPresent);
sv_assign_field(cfg.RVS, CVA6Cfg.RVS);
sv_assign_field(cfg.RVU, CVA6Cfg.RVU);
sv_assign_field(cfg.SoftwareInterruptEn, CVA6Cfg.SoftwareInterruptEn);
sv_assign_field(cfg.HaltAddress, CVA6Cfg.HaltAddress);
sv_assign_field(cfg.ExceptionAddress, CVA6Cfg.ExceptionAddress);
sv_assign_field(cfg.RASDepth, CVA6Cfg.RASDepth);
sv_assign_field(cfg.BTBEntries, CVA6Cfg.BTBEntries);
sv_assign_field(cfg.BPType, CVA6Cfg.BPType);
sv_assign_field(cfg.BHTEntries, CVA6Cfg.BHTEntries);
sv_assign_field(cfg.BHTHist, CVA6Cfg.BHTHist);
sv_assign_field(cfg.InstrTlbEntries, CVA6Cfg.InstrTlbEntries);
sv_assign_field(cfg.DataTlbEntries, CVA6Cfg.DataTlbEntries);
sv_assign_field(cfg.SharedTlbDepth, CVA6Cfg.SharedTlbDepth);
sv_assign_field(cfg.UseSharedTlb, CVA6Cfg.UseSharedTlb);
sv_assign_field(cfg.SvnapotEn, CVA6Cfg.SvnapotEn);
sv_assign_field(cfg.VpnLen, VpnLen);
sv_assign_field(cfg.PtLevels, PtLevels);
sv_assign_field(cfg.DmBaseAddress, CVA6Cfg.DmBaseAddress);
sv_assign_field(cfg.TvalEn, CVA6Cfg.TvalEn);
sv_assign_field(cfg.DirectVecOnly, CVA6Cfg.DirectVecOnly);
sv_assign_field(cfg.NrPMPEntries, CVA6Cfg.NrPMPEntries);
sv_assign_field(cfg.PMPCfgRstVal, CVA6Cfg.PMPCfgRstVal);
sv_assign_field(cfg.PMPAddrRstVal, CVA6Cfg.PMPAddrRstVal);
sv_assign_field(cfg.PMPEntryReadOnly, CVA6Cfg.PMPEntryReadOnly);
sv_assign_field(cfg.PMPNapotEn, CVA6Cfg.PMPNapotEn);
sv_assign_field(cfg.NOCType, CVA6Cfg.NOCType);
sv_assign_field(cfg.NrNonIdempotentRules, CVA6Cfg.NrNonIdempotentRules);
sv_assign_field(cfg.NonIdempotentAddrBase, CVA6Cfg.NonIdempotentAddrBase);
sv_assign_field(cfg.NonIdempotentLength, CVA6Cfg.NonIdempotentLength);
sv_assign_field(cfg.NrExecuteRegionRules, CVA6Cfg.NrExecuteRegionRules);
sv_assign_field(cfg.ExecuteRegionAddrBase, CVA6Cfg.ExecuteRegionAddrBase);
sv_assign_field(cfg.ExecuteRegionLength, CVA6Cfg.ExecuteRegionLength);
sv_assign_field(cfg.NrCachedRegionRules, CVA6Cfg.NrCachedRegionRules);
sv_assign_field(cfg.CachedRegionAddrBase, CVA6Cfg.CachedRegionAddrBase);
sv_assign_field(cfg.CachedRegionLength, CVA6Cfg.CachedRegionLength);
sv_assign_field(cfg.MaxOutstandingStores, CVA6Cfg.MaxOutstandingStores);
sv_assign_field(cfg.DebugEn, CVA6Cfg.DebugEn);
sv_assign_field(cfg.SDTRIG, CVA6Cfg.SDTRIG);
sv_assign_field(cfg.Mcontrol6, CVA6Cfg.Mcontrol6);
sv_assign_field(cfg.Icount, CVA6Cfg.Icount);
sv_assign_field(cfg.Etrigger, CVA6Cfg.Etrigger);
sv_assign_field(cfg.Itrigger, CVA6Cfg.Itrigger);
sv_assign_field(cfg.NonIdemPotenceEn, (CVA6Cfg.NrNonIdempotentRules > 0) && (CVA6Cfg.NonIdempotentLength[0] > 0));
sv_assign_field(cfg.AxiBurstWriteEn, CVA6Cfg.AxiBurstWriteEn);
sv_assign_field(cfg.ICACHE_SET_ASSOC, CVA6Cfg.IcacheSetAssoc);
sv_assign_field(cfg.ICACHE_SET_ASSOC_WIDTH, CVA6Cfg.IcacheSetAssoc > 1 ? clog2(CVA6Cfg.IcacheSetAssoc) : CVA6Cfg.IcacheSetAssoc);
sv_assign_field(cfg.ICACHE_INDEX_WIDTH, ICACHE_INDEX_WIDTH);
sv_assign_field(cfg.ICACHE_TAG_WIDTH, cfg.PLEN - ICACHE_INDEX_WIDTH);
sv_assign_field(cfg.ICACHE_LINE_WIDTH, CVA6Cfg.IcacheLineWidth);
sv_assign_field(cfg.ICACHE_USER_LINE_WIDTH, ICACHE_USER_LINE_WIDTH_v);
sv_assign_field(cfg.DCacheType, CVA6Cfg.DCacheType);
sv_assign_field(cfg.DcacheIdWidth, CVA6Cfg.DcacheIdWidth);
sv_assign_field(cfg.DCACHE_SET_ASSOC, CVA6Cfg.DcacheSetAssoc);
sv_assign_field(cfg.DCACHE_SET_ASSOC_WIDTH, CVA6Cfg.DcacheSetAssoc > 1 ? clog2(CVA6Cfg.DcacheSetAssoc) : CVA6Cfg.DcacheSetAssoc);
sv_assign_field(cfg.DCACHE_INDEX_WIDTH, DCACHE_INDEX_WIDTH);
sv_assign_field(cfg.DCACHE_TAG_WIDTH, cfg.PLEN - DCACHE_INDEX_WIDTH);
sv_assign_field(cfg.DCACHE_LINE_WIDTH, CVA6Cfg.DcacheLineWidth);
sv_assign_field(cfg.DCACHE_USER_LINE_WIDTH, DCACHE_USER_LINE_WIDTH_v);
sv_assign_field(cfg.DCACHE_USER_WIDTH, CVA6Cfg.AxiUserWidth);
sv_assign_field(cfg.DCACHE_OFFSET_WIDTH, DCACHE_OFFSET_WIDTH);
sv_assign_field(cfg.DCACHE_NUM_WORDS, pow2(DCACHE_INDEX_WIDTH - DCACHE_OFFSET_WIDTH));
sv_assign_field(cfg.DCACHE_MAX_TX, pow2(CVA6Cfg.MemTidWidth));
sv_assign_field(cfg.DcacheFlushOnFence, CVA6Cfg.DcacheFlushOnFence);
sv_assign_field(cfg.DcacheFlushOnFenceI, CVA6Cfg.DcacheFlushOnFenceI);
sv_assign_field(cfg.DcacheInvalidateOnFlush, CVA6Cfg.DcacheInvalidateOnFlush);
sv_assign_field(cfg.DATA_USER_EN, CVA6Cfg.DataUserEn);
sv_assign_field(cfg.WtDcacheWbufDepth, CVA6Cfg.WtDcacheWbufDepth);
sv_assign_field(cfg.FETCH_USER_WIDTH, CVA6Cfg.FetchUserWidth);
sv_assign_field(cfg.FETCH_USER_EN, CVA6Cfg.FetchUserEn);
sv_assign_field(cfg.AXI_USER_EN, AXI_USER_EN_v);
sv_assign_field(cfg.FETCH_WIDTH, CVA6Cfg.SuperscalarEn ? 64 : 32);
sv_assign_field(cfg.FETCH_ALIGN_BITS, clog2(cfg.FETCH_WIDTH / 8));
sv_assign_field(cfg.INSTR_PER_FETCH, cfg.FETCH_WIDTH / (CVA6Cfg.RVC ? 16 : 32));
sv_assign_field(cfg.LOG2_INSTR_PER_FETCH, cfg.INSTR_PER_FETCH > 1 ? clog2(cfg.INSTR_PER_FETCH) : 1);
sv_assign_field(cfg.ModeW, ModeW_v);
sv_assign_field(cfg.ASIDW, ASIDW_v);
sv_assign_field(cfg.VMIDW, VMIDW_v);
sv_assign_field(cfg.PPNW, PPNW_v);
sv_assign_field(cfg.GPPNW, GPPNW_v);
sv_assign_field(cfg.MODE_SV, MODE_SV_v);
sv_assign_field(cfg.SV, SV_v);
sv_assign_field(cfg.SVX, SVX_v);
sv_assign_field(cfg.X_NUM_RS, cfg.NrRgprPorts / cfg.NrIssuePorts);
sv_assign_field(cfg.X_ID_WIDTH, cfg.TRANS_ID_BITS);
sv_assign_field(cfg.X_RFR_WIDTH, cfg.XLEN);
sv_assign_field(cfg.X_RFW_WIDTH, cfg.XLEN);
sv_assign_field(cfg.X_NUM_HARTS, 1);
sv_assign_field(cfg.X_HARTID_WIDTH, cfg.XLEN);
sv_assign_field(cfg.X_DUALREAD, 0);
sv_assign_field(cfg.X_DUALWRITE, 0);
sv_assign_field(cfg.X_ISSUE_REGISTER_SPLIT, 0);
return cfg;
